name: CocoaPods Trunk

on:
  push:
    tags:
      - "*.*.*"

jobs:
  pod_trunk:
    runs-on: macos-latest
    timeout-minutes: 10
  
    steps:
    - uses: actions/checkout@v3

    - name: Setup ruby
      uses: ruby/setup-ruby@v1
      with:
        ruby-version: '3.0'
        bundler-cache: true

    - name: Switch Xcode
      run: sudo xcode-select -s /Applications/Xcode_13.4.1.app/Contents/Developer

    - name: Trunk push
      env:
        COCOAPODS_TRUNK_TOKEN: ${{ secrets.COCOAPODS_TRUNK_TOKEN }}
      timeout-minutes: 30
      run: bundle exec pod trunk push AnyErrorConvertible.podspec
