name: Test

on:
  push: {}
  pull_request: {}

jobs:
  test:
    strategy:
      matrix:
        version: [ {os: 'macos-12', xcode: '13.4.1' }, {os: 'macos-12', xcode: '13.3.1' }, {os: 'macos-12', xcode: '13.2.1' }, {os: 'macos-12', xcode: '13.1' }, {os: 'macos-11', xcode: '13.0' }, {os: 'macos-11', xcode: '12.5.1' } ]

    runs-on: ${{ matrix.version.os }}

    steps:
    - uses: actions/checkout@v3

    - name: Switch Xcode
      run: sudo xcode-select -s /Applications/Xcode_${{ matrix.version.xcode }}.app/Contents/Developer

    - name: Run tests
      run: swift test

  pod_lint:
    runs-on: macos-12

    steps:
    - uses: actions/checkout@v3
    - uses: ruby/setup-ruby@v1
      name: Setup Ruby
      with:
        ruby-version: '3.0'
        bundler-cache: true
    - name: Lint podspec
      run: |
        bundle exec pod lib lint AnyErrorConvertible.podspec --verbose
