name: Test

on:
  push: {}
  pull_request: {}

jobs:
  test:
    strategy:
      matrix:
        os: ['macos-12', 'macos-11', 'macos-10.15', 'ubuntu-20.04']

    runs-on: ${{ matrix.os }}

    steps:
    - uses: actions/checkout@v3
    - name: Run tests
      run: swift test

  pod_lint:
    runs-on: macos-12

    steps:
    - uses: actions/checkout@v3
    - uses: ruby/setup-ruby@v1
      name: Setup Ruby
      with:
        bundler-cache: true
    - name: Lint podspec
      run: |
        bundle exec pod lib lint AnyErrorConvertible.podspec
